### ISSUE TITLE
Protoc Version 

### ISSUE THREAD

**Issue by Darshana-Das-K** [bruce30262/libprotobuf-mutator_fuzzing_learning#13]
I tried fuzzing a sample program that utilizes the libprotobuf-mutator but encountered errors. When fuzzing programs that do not utilize libprotobuf-mutator, there are no errors. The errors occurred due to missing or incompatible header files of protobuf.

1. I had successfully built the LLVM Project.

2.  There were no errors in building libprotobuf-mutator.

>  "By default, the system-installed version of protobuf is used. However, on some systems, the system version is too old. You can pass LIB_PROTO_MUTATOR_DOWNLOAD_PROTOBUF=ON to CMake to automatically download and build a working version of protobuf."
 

  Since the above was mentioned in the GitHub repository of libprotobuf-mutator, I set the above-mentioned flag. There is a directory libprotobuf-mutator in the directory "/usr/local/include". So, I think that the header files of libprotobuf mutator are properly installed. However, there were some incompatibilities of header files with the protoc (protobuf compiler) version, resulting in errors.
4. When I built the libprotobuf-mutator, it had a protoc in the directory "/libprotobuf-mutator/build/external.protobuf/bin/protoc-25.2.0". I used this protoc by exporting the path, but I run into error that runtime_version.h was not found.

5. Also, there was a system-installed version of protoc that can be installed using the package manager, with the version: 

> "Package: protobuf-compiler Version: 3.12.4-1ubuntu7.22.04.1"

 Additionally, there were header files of protoc in the directory /usr/include/google/protobuf.

6. I uninstalled the version of protoc that was installed from the package manager and then I rebuilt the libprotobuf-mutator, but then the header files were missing. I again installed the protoc from the package manager, but then there were some incompatibilities of header files with the protoc version, resulting in errors. From this, I derive that the header files of the protoc which are with libprotobuf-mutator are not installed.

7. So, I tried building protobuf from source. I built the latest version of protobuf. Still, the header files were not in the /usr/include directory. And the errors of missing header files persisted. So, I copied the header files to the /usr/include directory and tried again. But then I got the error:

```
In file included from test_proto.cc:2:
./genfiles/ast.pb.h:15:2: error: "This file was generated by a newer version of protoc which is"
   15 | #error "This file was generated by a newer version of protoc which is"
      |  ^
./genfiles/ast.pb.h:16:2: error: "incompatible with your Protocol Buffer headers. Please update"
   16 | #error "incompatible with your Protocol Buffer headers. Please update"
      |  ^
In file included from calc.cc:2:
In file included from ./genfiles/ast.pb.h:26:
/usr/include/google/protobuf/io/coded_stream.h:110:10: fatal error: 'absl/log/absl_check.h' file not found
  110 | #include "absl/log/absl_check.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~
4 errors generated.
```

Note: The absl library is installed.

8. I also tried another way. Since the version of protoc is 25.2.0 in the libprotobuf-mutator, I thought that it probably requires this version of protoc. So I built that version of protoc from source, but there were errors in building.
Should I try building the protobuf version 25.2.0 again?

Kindly give me any insights that could resolve this and I can properly perform structure aware fuzzing in libfuzzer using libprotobuf-mutator. I understand that the points mentioned may be cluttered. Kindly notify me if it is too cluttered. Thank you for your time.

**Comment by bruce30262** [comment]
Hello @Darshana-Das-K,

I would suggest that you uninstall all version of `protoc` and re-install it from `libprotobuf-mutator`. Notice that this repo won't work with the latest `libprotobuf-mutator`, it is recommended to switch to commit `af3bb1` before compile & installing the libraries ( your `protoc` version in `libprotobuf-mutator` is `25.2.0`, meaning you're not using the compatible version ). This is mentioned in the README file, make sure you read all of them.  

BTW I found a guy made a [Dockerfile](https://github.com/Hank0438/libprotobuf-mutator_fuzzing_learning/blob/master/Dockerfile) for this repo. Maybe you'll find that useful ( I haven't try it yet ).

**Comment by Darshana-Das-K** [comment]
Dear @bruce30262, 
Thank you for your response. I understand that this repo will not work with the older version of protoc. I apologise for missing that out.  Though I prefer the latest version of protoc, I will install the older version as said. But If I want to install the newer version (hope that this is not out of the scope for asking here),  I remember I had uninstalled all versions of protoc and only installed the libprotobuf-mutator,  should I copy the bin of protoc in the build directory to /usr/local/bin?  When I run the program without doing this and by just exporting the path of the protoc in the build directory, the errors were that the header files, google/protobuf were missing. So should I copy the header files from the build directory to the /usr/local/include directory? Is the above caused because the libprotobuf-mutator was not installed properly?

Kindly provide me with any insights if this is not out of the scope for asking here. Thanks a lot for your time.

**Comment by bruce30262** [comment]
> So should I copy the header files from the build directory to the /usr/local/include directory? 

You don't have to do that, just follow the instructions in README and you are ready to go.

> should I copy the bin of protoc in the build directory to /usr/local/bin

You don't have to do that either, however make sure that `PROTOBUF_DIR` variable points to the `external.protobuf` directory in the Makefile of [1_simple_protobuf](https://github.com/bruce30262/libprotobuf-mutator_fuzzing_learning/tree/master/1_simple_protobuf).

**Comment by Darshana-Das-K** [comment]
Thanks for the response

**Comment by Darshana-Das-K** [comment]
Dear @bruce30262,
I reinstalled libprotobuf-mutator(older version). I compiled the test.proto and then I tried to run the test_proto.cc.

I ran into the error

> 
> /usr/bin/ld: /tmp/test_proto-a996ec.o: in function `main':
> test_proto.cc:(.text.main[main]+0x0): multiple definition of `main'; /usr/local/lib/clang/19/lib/x86_64-unknown-linux-gnu/libclang_rt.fuzzer.a(FuzzerMain.cpp.o):/home/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:19: first defined here
> /usr/bin/ld: /tmp/test_proto-a996ec.o: in function `main':
> test_proto.cc:(.text.main[main]+0x347): undefined reference to `TEST::~TEST()'
> /usr/bin/ld: test_proto.cc:(.text.main[main]+0x3f1): undefined reference to `TEST::~TEST()'
> /usr/bin/ld: /tmp/test_proto-a996ec.o: in function `TEST::TEST()':
> test_proto.cc:(.text._ZN4TESTC2Ev[_ZN4TESTC2Ev]+0x57): undefined reference to `TEST::TEST(google::protobuf::Arena*, bool)'
> /usr/bin/ld: /tmp/test_proto-a996ec.o: in function `google::protobuf::internal::ArenaStringPtr::Set(char const*, google::protobuf::Arena*)':
> test_proto.cc:(.text._ZN6google8protobuf8internal14ArenaStringPtr3SetEPKcPNS0_5ArenaE[_ZN6google8protobuf8internal14ArenaStringPtr3SetEPKcPNS0_5ArenaE]+0x195): undefined reference to `google::protobuf::internal::ArenaStringPtr::Set(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::Arena*)'
> /usr/bin/ld: /usr/local/lib/clang/19/lib/x86_64-unknown-linux-gnu/libclang_rt.fuzzer.a(FuzzerMain.cpp.o): in function `main':
> FuzzerMain.cpp:(.text.main+0x12): undefined reference to `LLVMFuzzerTestOneInput'
> clang++: error: linker command failed with exit code 1 (use -v to see invocation)

Why is this? 
I used below command to compile protobuf message using protoc.

> /home/libprotobuf-mutator/build/external.protobuf/bin/protoc --proto_path=. --cpp_out=. test.proto

and I use the below command to compile test_proto.cc

> clang++ -fsanitize=fuzzer,address -I /usr/local/include -I /usr/local/include/libprotobuf-mutator -I /home/libprotobuf-mutator/build/external.protobuf/include -L /usr/local/lib test_proto.cc -o sample_program -lprotobuf-mutator

Is it error in my commands or in my installation?

**Comment by bruce30262** [comment]
You shouldn't compile test_proto.cc with the `-fsanitize=fuzzer,address` flag. Please use the exact command in the Makefile to compile test_proto binary. 

Also please make sure you read and follow the instructions in README before asking questions. If you follow all the steps in README and still ran into issue, then that's the issue you have to report, otherwise please deal with the issue yourself ( I know this sounds harsh but apparently you added the flag yourself and ran into that error, so there's nothing to do with the original command in the Makefile. )

**Comment by Darshana-Das-K** [comment]
I apologize for any inconvenience caused. As someone new to this, I've been stuck for a while. Thank you for your patience and time.
