### ISSUE TITLE
[Research] How to parse and mutate a protobuf structure

### ISSUE THREAD

**Issue by bruce30262** [bruce30262/libprotobuf-mutator_fuzzing_learning#3]
For now the custom mutator in `4_libprotobuf_aflpp_custom_mutator` will NOT process the input from AFL++, meaning it will not process the input in `in/`. I remember I want to do something like:  

```c++
TEST input = protobuf_mutator::ParseTextMessage(test_case);  // test_case == "a:1\nb: 'AAAA'"
protobuf_mutator::mutate(input); // THIS IS NOT A VALID CALL THOUGH
string raw_data = ProtoToData(input);
..................
```  

But in the AFL++'s custom mutator it always failed while parsing the input data because AFL++ will always pass an invalid `TEST` text message into the custom mutator function ( most of them are incomplete input data from `in/` ). Gotta do some research and see if this is doable.

**Comment by vanhauser-thc** [comment]
What would you need?

**Comment by bruce30262** [comment]
@vanhauser-thc I've been busy lately and didn't have time to look into this issue, so I'm not sure what I really need.  

For now I'm guessing that AFL++ might have to find a way to make sure that the data passed into `afl_custom_fuzz()` has to be a valid protobuf data, so later we can parse and mutate the data without running into the parsing error or something like that.  

 However, I notice that in [afl-libprotobuf-mutator](https://github.com/thebabush/afl-libprotobuf-mutator/blob/master/src/mutator.cc#L57) it did not handle the input data with parsing routine -- it just pass it to `LLVMFuzzerCustomMutator` and let it do the mutation. This is exactly what I want -- let libfuzzer handle the protobuf format and do the mutation base on that format, without me doing everything myself. I remember trying to do what afl-libprotobuf-mutator does but failed due to several issues ( can't remember what issues though :/ ) . Maybe I was missing something.  

I think I'll take some time read the source code of afl-libprotobuf-mutator and see if I can create an example with libfuzzer handling the parsing and mutating the protobuf message. I'll let you know if I need anything from AFL++ :)  ( Right now all I need is more time Q_Q )

**Comment by bruce30262** [comment]
Done in [5_libprotobuf_aflpp_custom_mutator_input](https://github.com/bruce30262/libprotobuf-mutator_fuzzing_learning/tree/master/5_libprotobuf_aflpp_custom_mutator_input). The example leverage the serialization/deserialization of the protobuf message and is able to parse and mutate the custom protobuf data in our custom mutator.

Spent like two days trying to integrate libfuzzer into the custom mutator but failed miserably. The reason is that in libprotobuf-mutator's [libfuzzer_mutator.cc](https://github.com/google/libprotobuf-mutator/blob/master/src/libfuzzer/libfuzzer_mutator.cc#L50) it shows that it requires libfuzzer's own `LLVMFuzzerMutate` to overwrite the default one ( which is defined as a weak symbol ) during the building process. To make libfuzzer's `LLVMFuzzerMutate` work, we'll have to initialize a `MutationDispatcher` first, which is done by `FuzzerDriver()`. And there's no easy way to call `FuzzerDriver()` in our custom mutator, even if we managed to do it, we'll probably stuck inside `FuzzerDriver()` since this function drives the libfuzzer's fuzzing routine. I highly doubt that afl-libprotobuf-mutator is able to parse and mutate the data with a single `LLVMFuzzerCustomMutator` call. Maybe the parsing part would work but definitely not the mutation part, since in the end it'll always call the default `LLVMFuzzerMutate`, which does nothing but `return 0;`.
