### ISSUE TITLE
Update the example to fit the latest environment & AFL++

### ISSUE THREAD

**Issue by bruce30262** [bruce30262/libprotobuf-mutator_fuzzing_learning#4]
[ 2020/12/16 ]
Try make the code works in the following environments:  
* Ubuntu 20.04
* Clang 11
* AFL++ 3.0.0c

> If I have time though ... Orz

**Comment by bruce30262** [comment]
Done via #5

**Comment by vanhauser-thc** [comment]
now make a tweet :)
