### ISSUE TITLE
Will "mutated_out" cause memory leaks?

### ISSUE THREAD

**Issue by huanggh666** [bruce30262/libprotobuf-mutator_fuzzing_learning#9]
In the “afl_custom_fuzz” function, mutated_out allocates a piece of memory and assigns the pointer to out_buf. In AFLPP this piece of memory is not released, will this cause memory leak?

**Comment by vanhauser-thc** [comment]
This will be a memory leak yes. In older times afl-fuzz would free the memory but that led to problems so this was changed and this code here needs to be updated.

**Comment by bruce30262** [comment]
Guess it's time to update some code😅. It'll probably take some time though, it's been a while since I look at the custom mutator in AFL++, might have to re-learn all the stuff again 👴. As for the memory leak, I think I'll move those buffer to static variable, and only reallocate if needed.

**Comment by bruce30262** [comment]
The issue should be fixed via #10 ( mainly 27168d4 & 0ffc7c2 ). I decide to use custom mutator structure in the end ( [here's a nice example](https://github.com/airbus-seclab/AFLplusplus-blogpost/blob/b0cfc7016bd60cf998969d79a78eabd8471c78eb/src/mutator/custom_mutator.cpp) ).  Feel free to reopen the issue if you have any problem, thanks for reporting !
